
import React from 'react';
import { AccountType, TransactionType } from '../../types';
import FinancialGoals from './FinancialGoals';

interface BottomGridProps {
  mode: AccountType;
  onRequestNewTransaction: (type: TransactionType) => void;
  onRequestReportPDF: () => void;
}

const BottomGrid: React.FC<BottomGridProps> = ({ mode, onRequestNewTransaction, onRequestReportPDF }) => {
  return (
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
       {/* Passing mode to FinancialGoals to ensure correct account type for transactions generated by goal contributions */}
       <FinancialGoals mode={mode} />

       <div className="bg-white p-8 rounded-[40px] shadow-sm border border-slate-100">
          <h3 className="text-lg font-black text-slate-900 tracking-tight mb-8">Ações Recomendadas</h3>
          <div className="grid grid-cols-2 gap-4">
            <button onClick={() => onRequestNewTransaction('INCOME')} className="flex flex-col items-center justify-center p-6 bg-slate-50 border border-slate-100 rounded-[32px] hover:bg-orange-500 hover:text-white transition-all group">
              <div className="w-12 h-12 bg-white rounded-2xl flex items-center justify-center shadow-sm mb-3 group-hover:bg-orange-400 transition-colors">
                 <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" className="text-orange-600 group-hover:text-white"><path d="M12 5v14"/><path d="M5 12h14"/></svg>
              </div>
              <span className="text-xs font-black uppercase tracking-tight">Nova Venda</span>
            </button>
            <button onClick={() => onRequestNewTransaction('EXPENSE')} className="flex flex-col items-center justify-center p-6 bg-slate-50 border border-slate-100 rounded-[32px] hover:bg-rose-600 hover:text-white transition-all group">
              <div className="w-12 h-12 bg-white rounded-2xl flex items-center justify-center shadow-sm mb-3 group-hover:bg-rose-500 transition-colors">
                 <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" className="text-rose-600 group-hover:text-white"><path d="M5 12h14"/></svg>
              </div>
              <span className="text-xs font-black uppercase tracking-tight">Registrar Gasto</span>
            </button>
            <button onClick={onRequestReportPDF} className="flex flex-col items-center justify-center p-6 bg-slate-50 border border-slate-100 rounded-[32px] hover:bg-slate-900 hover:text-white transition-all group">
              <div className="w-12 h-12 bg-white rounded-2xl flex items-center justify-center shadow-sm mb-3 group-hover:bg-slate-800 transition-colors">
                 <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" className="text-slate-900 group-hover:text-white"><path d="M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2"/><rect x="8" y="2" width="8" height="4" rx="1" ry="1"/></svg>
              </div>
              <span className="text-xs font-black uppercase tracking-tight">Relatório PDF</span>
            </button>
            <button onClick={() => onRequestNewTransaction('EXPENSE')} className="flex flex-col items-center justify-center p-6 bg-slate-50 border border-slate-100 rounded-[32px] hover:bg-emerald-600 hover:text-white transition-all group">
              <div className="w-12 h-12 bg-white rounded-2xl flex items-center justify-center shadow-sm mb-3 group-hover:bg-emerald-500 transition-colors">
                 <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" className="text-emerald-600 group-hover:text-white"><circle cx="8" cy="21" r="1"/><circle cx="19" cy="21" r="1"/><path d="M2.05 2.05h2l2.66 12.42a2 2 0 0 0 2 1.58h9.78a2 2 0 0 0 1.95-1.57l1.65-7.43H5.12"/></svg>
              </div>
              <span className="text-xs font-black uppercase tracking-tight">Comprar</span>
            </button>
          </div>
       </div>
    </div>
  );
};

export default BottomGrid;
